url: https://api.devnet.solana.com
stats:
  - source: 4YFq9y5f5hi77Bq8kDCE6VgqoAqKGSQN87yW9YeGybpNfqKUG4WxnwhboHGUeXjY7g8262mhL1kCCM9yy8uGvdj7
    dest: 5z1K2vxQHZF38Y7AqaFbLmvAmz1UJVe6iXs2P5wH5wXL
    amount: 10
